#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a until loop

count=0

# Using until loop to display "Best School" 10 times
until [ $count -ge 10 ]
do
    echo "Best School"
    ((count++))
done
