#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop

count=1

# Using a while loop to display "Best School" 10 times
while [ $count -lt 10 ]
do
    if [ $count -eq 3 ]
    then 
        echo "bad luck"
        ((count++))
    elif [ $count -eq 7 ]
    then
        echo "good luck"
        ((count++))
    else
        echo "Best School"
        ((count++))
    fi
done
