#!/usr/bin/env bash
# description of code
if [ -e "school" ]; then
    echo "school file exists"
    if [ -d "school" ]; then
        if [ -s "school" ]; then
                echo "school file is not empty"
            else
                echo "school file is empty"
            fi
    else
        if [ -s "school" ]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
